- repo: https://github.com/PyCQA/flake8
  rev: 3.9.2  
  hooks:
    - id: flake8
      language_version: python3 

- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.5.7 
  hooks:
    - id: autopep8
      language_version: python3